### ISSUE TITLE
README.md的一个笔误

### ISSUE THREAD

**Issue by liuxueyang** [slackwarecn-slackbuilds/librime#2]
README.md里面的这句 `mv leveldb leveldb-1.9.0` 好像有点问题。

应该是这样：`mv leveldb-1.9 leveldb-1.9.0`

**Comment by liuxueyang** [comment]
另外，`wget $DOWNLOAD`之后，要重命名一下：`mv rime-1.2.9.tar.gz librime-rime-1.2.9.tar.gz`

**Comment by nnnewb** [comment]
该次[提交](https://github.com/slackwarecn-slackbuilds/librime/commit/3464cb75278a1e3b1d8c9990e90ecef94d6270b4)中已经修复，手里没有环境无法确认是否能直接执行示例代码。
如果确认问题已经修复，请直接关闭issue，如果有更多的问题，请提出。
感谢提供意见。
